# Use non container-based environment (becouse of Docker) with Ubuntu Trusty
dist: trusty
sudo: required

language: node_js
node_js:
  - "8"

# Cache node_modules and gcloud SDK between builds
cache:
  directories:
     - ./node_modules

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
    - PROJECT_ID=automated-development-process
    - COMPUTE_ZONE=us-central1-a
    - CLUSTER_NAME=cluster-1
    - DOCKER_IMAGE_NAME=average-salary

install:
  - npm install

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

before_deploy:
  - gcloud version
  - sudo apt-get -qq update
  - sudo apt-get -qq install kubectl

deploy:
  - provider: script
    script: ./.continous-delivery/deploy.sh
    skip_cleanup: true
    on:
      branch: master
